version: '3'

services:
  instance:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: hoyolab-auto
    network_mode: bridge
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
    environment:
      TZ: Asia/Shanghai
