version: '3'

services:
  instance:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: hoyolab-auto
    network_mode: bridge
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data/cache.json:/app/data/cache.json:ro
    environment:
      TZ: Asia/Shanghai
